mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 21 11:41:05 2020

@author: Daan
"""

from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [    
    path('', views.IndexView.as_view(), name='index'),
    path('topics/', views.topics, name='topics'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/polls/models.py
import datetime
import requests

from django.db import models
from django.utils import timezone
from django.db.models import F, Count

class Topic(models.Model):
    topic_text = models.CharField(max_length=200)
    question_count = models.IntegerField(default=0)

    def __str__(self):
        return self.topic_text
    
    def get_wikipedia_article(self):
        url = "None"
        r = requests.get("https://en.wikipedia.org/wiki/" + str(self.topic_text))
        if r.status_code == 200:
            url = r.url
        return url
    get_wikipedia_article.short_description = 'Wiki Page'

class Question(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, blank=True, null=True)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.template import loader

from .models import Choice, Question, Topic

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')

class TopicView(generic.ListView):
    template_name = 'polls/topics.html'
    context_object_name = 'topic_list'
    
    def get_queryset(self):
        return Topic.objects.all()

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def topics(request):
    template = loader.get_template('polls/topics.html')
    
    topic_list = Topic.objects.all().order_by('-question_count')
    context = {'topic_list': topic_list}
    
    for topic in topic_list:
        count = Question.objects.filter(topic__topic_text=topic).count()
        topic.question_count = count
        topic.save()
    return HttpResponse(template.render(context, request))

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>detail</title>
  </head>
  <body>
    <h1>{{ question.question_text }}</h1>
    
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    
    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
    </form>
    <a href="{% url 'polls:index' %}">Back to overview</a>
  </body>
</html>

mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>polls</title>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
  </head>
  <body>
    <div class="center">
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a> A question about {{ question.topic }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
    <a href="{% url 'polls:topics' %}">Check out all the topics</a>
    </div>
  </body>
</html>

mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>detail</title>
  </head>
  <body>
    <h1>{{ question.question_text }}</h1>
    
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>
    
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
    <a href="{% url 'polls:index' %}">Back to overview</a>
  </body>
</html>

mysite/polls/templates/polls/topics.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>topics</title>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
  </head>
  <body>
    <div class="center">
    <p>
    The Topics are:
    </p>
    {% if topic_list %}
        <ul>
        {% for topic in topic_list %}
            <li>{{ topic.topic_text}} {{topic.question_count}}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No topics are available.</p>
    {% endif %}
    <a href="{% url 'polls:index' %}">Back to the questions</a>
    </div>
  </body>
</html>